import React from 'react'
import { View, StyleSheet, Pressable } from 'react-native'
import { ChevronLeft } from 'lucide-react-native'
import { TermsScreenProps } from '../navigation/types'
import { ScreenWrapper } from '../components/templates'
import { Text } from '../components/atoms'
import { tokens, space, layout } from '../design/tokens'

const SECTIONS = [
  {
    title: 'Acceptance of Terms',
    body: 'By accessing or using OMENORA, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.',
  },
  {
    title: 'Nature of Service',
    body: 'OMENORA provides AI-generated destiny and numerology reports for entertainment and self-reflection purposes. Reports are not a substitute for professional advice — medical, legal, financial, or psychological.',
  },
  {
    title: 'Payments & Refunds',
    body: 'OMENORA offers an auto-renewing Premium subscription, one-time purchases (such as the annual Calendar reading and individual Compatibility readings), and consumable conversation packs for Counsel. All purchases are billed through the app store you used to download the app (Apple App Store or Google Play). Premium subscriptions renew automatically at the end of each billing period unless you cancel at least 24 hours before the period ends; you can view, manage, or cancel a subscription at any time in your app store account settings. Refunds are handled by the app store, not by OMENORA directly: Apple users can request a refund at reportaproblem.apple.com, and Google Play users can request one through their Play Store order history.',
  },
  {
    title: 'Intellectual Property',
    body: 'All content, reports, and materials generated by OMENORA are owned by OMENORA or its licensors. You may not reproduce, distribute, or resell any report content without written permission.',
  },
  {
    title: 'Limitation of Liability',
    body: 'OMENORA is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from use of the service.',
  },
  {
    title: 'Governing Law',
    body: 'These terms are governed by applicable law. Any disputes shall be resolved through binding arbitration rather than court proceedings, except where prohibited by law.',
  },
  {
    title: 'Contact',
    body: 'For questions regarding these terms, contact us at support@omenora.com. Last updated: January 2026.',
  },
];

export const TermsScreen: React.FC<TermsScreenProps> = ({ navigation }) => (
  <ScreenWrapper
    scroll
    padded
    contentContainerStyle={styles.scroll}
  >
    <Pressable onPress={() => navigation.goBack()} style={styles.back} hitSlop={12}>
      <ChevronLeft size={24} color={tokens.text.secondary} />
    </Pressable>

    <Text variant="micro" color="accent" style={styles.eyebrow}>LEGAL</Text>
    <Text variant="display2" color="primary" style={styles.heading}>Terms of Service</Text>
    <Text variant="caption" color="tertiary" style={styles.lastUpdated}>Effective January 2026</Text>

    <View style={styles.rule} />

    {SECTIONS.map(({ title, body }) => (
      <View key={title} style={styles.section}>
        <Text variant="micro" color="tertiary" style={styles.sectionTitle}>{title}</Text>
        <Text variant="body" color="secondary">{body}</Text>
      </View>
    ))}
  </ScreenWrapper>
)

const styles = StyleSheet.create({
  scroll:       { paddingTop: space['4'], paddingBottom: space['16'] },
  back:         { marginBottom: space['8'], alignSelf: 'flex-start', minHeight: layout.tapTarget, justifyContent: 'center' },
  eyebrow:      { marginBottom: space['2'] },
  heading:      { marginBottom: space['2'] },
  lastUpdated:  { marginBottom: space['6'] },
  rule:         { height: StyleSheet.hairlineWidth, backgroundColor: tokens.border.subtle, marginBottom: space['8'] },
  section:      { marginBottom: space['8'] },
  sectionTitle: { marginBottom: space['2'] },
})
